services:
  php:
    build:
      context: .
      dockerfile: docker/php-dev/Dockerfile
    container_name: app-php-dev
    volumes:
      - ./application:/var/www/html
    environment:
      PHP_IDE_CONFIG: serverName=app
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: app-nginx
    ports:
      - "8080:80"
    volumes:
      - ./application/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:18.1-alpine3.23
    container_name: app-postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.4.0
    container_name: app-redis
    ports:
      - "6379:6379"

  loki-dating:
    image: grafana/loki:latest
    container_name: loki-dating
    volumes:
      - ./docker/grafana/loki-config.yml:/etc/loki/config.yml
    command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./docker/grafana/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki-dating

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - loki-dating

volumes:
  postgres_data:
